[tox]
envlist = lint, unit
skipsdist = True

[testenv:lint]
deps =
    ruff
commands =
    ruff check src tests

[testenv:unit]
deps =
    -r requirements.txt
    ops[testing]
    pytest
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    pytest -v tests/unit
